repos:
  - repo: 'https://github.com/psf/black'
    rev: 23.11.0
    hooks:
      - id: black
        files: src
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
      - id: ruff
        files: src
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.7.1
    hooks:
      - id: mypy
        args: ['--install-types', '--non-interactive', '--ignore-missing-imports']
        files: .
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout